from configuration.config import ENV

DATA_TABLE = ENV['DB_DATA_TABLE']
TEMPERATURE_TABLE = ENV['DB_TEMPERATURE_TABLE']
COEFFICIENTS_TABLE = ENV['DB_COEFFICIENTS_TABLE']
DEFAULT_IN_PATH = ENV['DEFAULT_INPUT_PATH']
DEFAULT_FILE = ENV['DEFAULT_FILE']
DATABASE = ENV['DATABASE_NAME']

ALL_TABLES = [
    DATA_TABLE,
    TEMPERATURE_TABLE,
    COEFFICIENTS_TABLE,
]