from os import environ as env

DATA_TABLE = env['DB_DATA_TABLE']
TEMPERATURE_TABLE = env['DB_TEMPERATURE_TABLE']
COEFFICIENTS_TABLE = env['DB_COEFFICIENTS_TABLE']
DEFAULT_IN_PATH = env['DEFAULT_INPUT_PATH']
DEFAULT_FILE = env['DEFAULT_FILE']

ALL_TABLES = [
    DATA_TABLE,
    TEMPERATURE_TABLE,
    COEFFICIENTS_TABLE,
]