from os import environ as env

__DATA_TABLE = env['DB_DATA_TABLE']
__TEMPERATURE_TABLE = env['DB_TEMPERATURE_TABLE']
__COEFFICIENTS_TABLE = env['DB_COEFFICIENTS_TABLE']
__DEFAULT_PATH = env['DEFAULT_PATH']

__ALL_TABLES = [
    __DATA_TABLE,
    __TEMPERATURE_TABLE,
    __COEFFICIENTS_TABLE,
]